[package]
name = "zicade"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "zicade"
path = "src/lib.rs"

[[bin]]
name = "zicade"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
zicade-auth = { path = "../../crates/zicade-auth" }
zicade-config = { path = "../../crates/zicade-config" }
zicade-observe = { path = "../../crates/zicade-observe" }
zicade-proxy = { path = "../../crates/zicade-proxy" }
zicade-routing = { path = "../../crates/zicade-routing" }
zicade-web = { path = "../../crates/zicade-web" }
zicade-win = { path = "../../crates/zicade-win" }

[dev-dependencies]
tokio = { workspace = true, features = ["signal"] }
zicade-config = { path = "../../crates/zicade-config" }
zicade-observe = { path = "../../crates/zicade-observe" }
zicade-proxy = { path = "../../crates/zicade-proxy" }
zicade-win = { path = "../../crates/zicade-win" }

[lints]
workspace = true
