[package]
name = "zicade-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zicade-auth = { path = "../zicade-auth" }

[dev-dependencies]
zicade-win = { path = "../zicade-win" }
base64 = { workspace = true }

[lints]
workspace = true
